# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-20 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interpreterfeedback',
            old_name='glossid',
            new_name='gloss_id',
        ),
    ]
