# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-17 13:44
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_map_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signfeedback',
            name='translation',
        ),
    ]
